### ISSUE TITLE
mana font not working

### ISSUE THREAD

**Issue by droxxa** [bbeny123/ChireTweaks#2]
I love this addon thank you!

One thing I've found as a Druid, the font for mana cannot be changed nor hidden.

![manafont](https://github.com/bbeny123/ChireTweaks/assets/155696499/85de4507-d302-4bd6-b3b0-f3a2245c9fbf)

**Comment by bbeny123** [comment]
fixed in 1.1.2: https://github.com/bbeny123/ChireTweaks/commit/82b964412790043f3c0c7a5887b9cbe2512121ba
